name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Maven
        run: |
          mvn clean compile package

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/atm-report-service:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/atm-report-service:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/atm-report-service:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/atm-report-service:latest

      - name: SSH into EC2 and update container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker stop atm-report-service || true
            docker rm atm-report-service || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/atm-report-service:latest
            docker run -d -p 80:8080 --name atm-report-service ${{ secrets.DOCKER_USERNAME }}/atm-report-service:latest
